# Add/remove 'critical' label if issue contains the words 'urgent' or 'critical'
indexing:
    - '(indexing)'
safe loading:
    - '(safe loading)'
token value:
    - '(token value)'
tx execution:
    - '(tx execution)'
tx missing:
    - '(tx missing)'
questions:
    - '(indexing)'
