# Add/remove 'critical' label if issue contains the words 'urgent' or 'critical'
safe loading:
    - '(safe loading|safe loading)'
tranasaction missing:
    - '(transaction missing|transaction missing)'
