# Add/remove 'critical' label if issue contains the words 'urgent' or 'critical'
safe_loading:
    - '(Safe_loading)'
token_balance:
    - '(Token Balance)'
token_missing:
    - '(Token Missing)'
tx_execution:
    - '(Tranasaction execution)'
tx_missing:
    - '(Tranasaction missing)'
other:
    - '(Other)'
